import pandas as pd
# genera_counts = pd.read_csv(r"C:\RESEARCH-PROJECT\IHMP\genera.counts (2).tsv", sep="\t")
# metadata = pd.read_csv(r"C:\RESEARCH-PROJECT\IHMP\metadata (1).tsv", sep="\t")
# mtb = pd.read_csv(r"C:\RESEARCH-PROJECT\IHMP\mtb.tsv", sep="\t")
# species = pd.read_csv(r"C:\RESEARCH-PROJECT\IHMP\species (4).tsv", sep="\t")
# species_counts = pd.read_csv(r"C:\RESEARCH-PROJECT\IHMP\species.counts (2).tsv", sep="\t")
# genera = pd.read_csv(r"C:\RESEARCH-PROJECT\IHMP\genera (1).tsv", sep="\t")
lda=pd.read_csv(r"C:\RESEARCH-PROJECT\IHMP\integrated_microbiome_dataset.tsv", sep="\t")
# print("Genera Counts Head:\n", genera_counts.head())
# print("Metadata Head:\n", metadata.head())
# print("MTB Head:\n", mtb.head())
# print("Species Counts Head:\n", species_counts.head())
# print("Species Head:\n", species.head())
# print("Genera Head:\n", genera.head())
print("LDA Head:\n", lda.head())
# print(lda.head())